HKCALL ; Hakeem hardening caller
START N DUZ,DIVIEN,FDA,ERR,X,Y,Z,WHEN
 D EN^XUP
 I $$GET^XPAR("SYS","XU VC CASE SENSITIVE") S X=$$UP^XLFSTR("abc")
 S WHEN=$$FMADD^XLFDT($$GET1^DIQ(4,DIVIEN,400000000),1)
 D:DUZ FILE^DIE("","FDA","ERR"),UPDATE^DIE("","FDA","IEN","ERR")
 S Y=$$GET1^DIQ(200,DUZ,.01),Z=$$FMADD^XLFDT(Y,7) D FILE^DIE("","FDA","ERR")
 D LOCAL
 G EXIT
 S FAKE="$$GET1^DIQ(2,DUZ,.01)" ; D FILE^DIE("","FDA","ERR")
LOCAL S X=1 Q
EXIT Q
